title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://alakesh-kalita.github.io/DSA

aux_links:
  Template Repository: https://alakesh-kalita.github.io/DSA
